swagger: '2.0'
info:
  title: 'Laravel Generator APIs'
  version: 1.0.0
basePath: /api/v1
paths: {  }
definitions: {  }
security:
  -
    jwt:
      - '*'
securityDefinitions:
  jwt:
    securityDefinition: jwt
    type: apiKey
    description: 'Jwt Auth'
    name: Authorization
    in: header
